### ISSUE TITLE
Changed host key and startup scripts locked

### ISSUE THREAD

**Issue by mthoodlum** [ispapp/ispapp-linux-client#3]
I generated a new host key on the demo server and then upgraded an OpenWRT device from firmware .81 to .82 by downloading the firmware to /tmp and performing a sysupgrade. The new host showed up in Unknown Hosts as expected. I updated the host key on the host view on the server to the newly generated key value. I then logged into the device on SSH and ran a reboot. The device did not reboot until I killed the init_collect.sh process. The device also did not successfully update until after the reboot.

**Comment by andrewhodel** [comment]
You have to reinstall the script.

**Comment by mthoodlum** [comment]
This is an OpenWRT host. The init_collect.sh needs to be more robust.

**Comment by andrewhodel** [comment]
This is the exact same issue as #1.
