### ISSUE TITLE
Ping charts errors

### ISSUE THREAD

**Issue by mthoodlum** [ispapp/ispapp-linux-client#4]
Ping charts show single digit ping round trip time values. This is not physically possible. This OpenWRT device is in Texas and is connected with a cable modem and it is pinging an Oregon based EC2 server.

I attached a recent packet capture.

<img width="776" alt="Screen Shot 2021-08-01 at 11 26 32 PM" src="https://user-images.githubusercontent.com/4017230/127804393-2097c630-6701-457b-88af-bad3629aa191.png">

[icmp.pcap.zip](https://github.com/ispapp/ispapp-linux-client/files/6914400/icmp.pcap.zip)

**Comment by andrewhodel** [comment]
The pcap file has a timestamp of 11:21 PM and the charts have a timestamp of 11:25:30 PM.

That means that this packet capture is not the same data as the chart data and therefore invalid in relation to this particular issue.  Both devices have synchronized time to the 10s of milliseconds as they both use NTP.

```
NTP can usually maintain time to within tens of milliseconds over the public Internet, and can achieve better than one millisecond accuracy in local area networks under ideal conditions. Asymmetric routes and network congestion can cause errors of 100 ms or more.
```

Provide this chart with the actual network traffic so I can properly debug, DOCUMENT, and resolve this issue from August 1st 2021.
